version: '3.3'
services: 
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: typegraphql
            POSTGRES_DB: typegraphql

    app:
        build: 
            context: .
            target: dev
        depends_on: 
            - postgres
        environment: 
            NODE_ENV: development
        ports: 
            - "4000:4000"
        volumes:
            - .:/app/
            - ./node_modules:/app/node_modules:rw
            - ./dist:/app/dist:rw
