version: '3.3'
services: 
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: typegraphql
            POSTGRES_DB: typegraphql

    app:
        build:
            context: .
            cache_from:
                - alexrozhnov/demo-typegraphql:app_latest
        image: alexrozhnov/demo-typegraphql:app_latest
        environment: 
            NODE_ENV: test
        depends_on: 
            - postgres
        ports: 
            - "4000:4000"
