version: '3.3'
services: 
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: typegraphql
            POSTGRES_DB: typegraphql

    app:
        build: .
        depends_on: 
            - postgres
        ports: 
            - "4000:4000"
